server:
  port: 3002
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 2MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.hzby.whc.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    druid:
      min-idle: 20
      max-active: 100
      max-wait: 6000
      time-between-eviction-runs-millis: 300000
      username: 
      password: 
      url: jdbc:mysql://localhost:3306/administration?useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 1000
    database: 0
    jedis:
      pool:
        max-active: 4
        max-idle: 8
        min-idle: 2
        max-wait: 100


logging:
  file:
    path: /administration